### PR TITLE
Now my strategy is up in the mid 90% success rate!

### PR DESCRIPTION
**Pull request by bbozzuto**
The code is spaghetti, I am contemplating it as an opportunity to try test automation as a means to refactor and clean it up.

### CODE REVIEW

**Comment by dshapiro1dev** [comment]
there are some conflicts - because I had added some functionality - eg: passing the revealed letters so far to the solver, and keeping statistics.

lets figure out how to resolve this - else if I accept the pull - it will overwrite?

**Comment by bbozzuto** [comment]
Yeah, I had to add that too. I can try to reconcile changes tonight

**Comment by dshapiro1dev** [comment]
Brian - should I try merge the conflicts - or are you thinking a different version on your end?
I'm going to code up the guesser improvements 
- and we need to connect both guessers  to the  pending generator functions?

**Comment by bbozzuto** [comment]
If you have time to try today, go for it. I may this evening, but my
schedule has been a bit of a mess

**Pull request closed without merging**
